import type { PrismaClient } from "@prisma/client";

const COLLECTION_OWNER = "Coordenação Administrativa";
const ANALYSIS_OWNER = "Head de Operações";
const STORAGE = "Banco de Indicadores IVMM";

export const commercialFunnelIndicatorCodes = ["COM-004", "COM-005", "COM-006", "COM-007", "FIN-004", "COM-008"];

const commercialFunnelIndicators = [
  {
    code: "COM-004",
    name: "Taxa de Resposta aos Leads",
    area: "COMERCIAL",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "CLIENTES",
    strategicObjective: "Garantir agilidade no primeiro contato e reduzir perdas de oportunidades.",
    type: "EFICIENCIA",
    level: "OPERACIONAL",
    polarity: "MAIOR_MELHOR",
    unit: "%",
    collectionFrequency: "DIARIA",
    analysisFrequency: "MENSAL",
    purpose: "Mensurar a capacidade da equipe comercial em responder rapidamente aos leads recebidos, assegurando que nenhum potencial paciente permaneça sem atendimento.",
    operationalDefinition: "Considera respondido todo lead que recebeu retorno humano ou automatizado personalizado dentro do fluxo oficial de atendimento do IVMM.",
    formula: "(Leads Respondidos / Leads Recebidos) x 100",
    numerator: "Leads respondidos",
    denominator: "Leads recebidos",
    inclusionCriteria: "WhatsApp; Instagram; Facebook; Site; Google; Indicação; Eventos; Campanhas patrocinadas.",
    exclusionCriteria: "Spam; Duplicidades; Mensagens de teste; Contatos internos.",
    sourceSystem: "Kommo CRM; WhatsApp Business; Meta Business Suite; Sistema de telefonia",
    storageLocation: STORAGE,
    collectionMethod: "A Coordenação Administrativa registra diariamente leads recebidos, leads respondidos e data/hora do primeiro contato; os dados operacionais devem ser conciliados com o Kommo CRM.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Conferência amostral mensal entre Kommo CRM e canais de atendimento.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Comercial; Dashboard Executivo",
    aiAgentName: "Agente Comercial IVMM",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "COM-005",
    name: "Taxa de Agendamento",
    area: "COMERCIAL",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "CLIENTES",
    strategicObjective: "Maximizar a conversão de leads respondidos em consultas agendadas.",
    type: "EFICIENCIA",
    level: "OPERACIONAL",
    polarity: "MAIOR_MELHOR",
    unit: "%",
    collectionFrequency: "DIARIA",
    analysisFrequency: "MENSAL",
    purpose: "Avaliar a eficiência da equipe comercial na condução do lead até o agendamento da primeira consulta.",
    operationalDefinition: "Considera agendado todo lead que possui consulta registrada no sistema com data e horário definidos.",
    formula: "(Leads Agendados / Leads Respondidos) x 100",
    numerator: "Leads agendados",
    denominator: "Leads respondidos",
    inclusionCriteria: "Primeira consulta agendada; Agendamento presencial; Agendamento por teleconsulta.",
    exclusionCriteria: "Cancelamentos antes da confirmação; Agendamentos duplicados; Agendamentos de teste.",
    sourceSystem: "Kommo CRM; Agenda eletrônica; Sistema de agendamento",
    storageLocation: STORAGE,
    collectionMethod: "A Coordenação Administrativa registra diariamente leads respondidos, leads convertidos em agendamento e canal de origem do lead; os dados operacionais devem ser conciliados com o Kommo CRM.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Conferência mensal entre Kommo CRM, agenda eletrônica e sistema de agendamento.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Comercial; Dashboard Executivo",
    aiAgentName: "Agente Comercial IVMM",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "COM-006",
    name: "Taxa de Comparecimento",
    area: "COMERCIAL",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "CLIENTES",
    strategicObjective: "Maximizar o aproveitamento dos agendamentos realizados, reduzindo o absenteísmo e aumentando a eficiência do funil comercial.",
    type: "EFICIENCIA",
    level: "OPERACIONAL",
    polarity: "MAIOR_MELHOR",
    unit: "%",
    collectionFrequency: "DIARIA",
    analysisFrequency: "MENSAL",
    purpose: "Mensurar o percentual de pacientes agendados que efetivamente comparecem à consulta.",
    operationalDefinition: "Considera comparecimento quando o paciente realiza atendimento presencial ou por telemedicina na data originalmente agendada.",
    formula: "(Número de Pacientes que Compareceram / Número de Pacientes Agendados) x 100",
    numerator: "Pacientes que compareceram",
    denominator: "Pacientes agendados",
    inclusionCriteria: "Primeira consulta; Consulta de retorno; Teleconsulta; Consulta confirmada.",
    exclusionCriteria: "Cancelamentos antecipados; Reagendamentos autorizados; Falecimento; Interdição do atendimento por fatores institucionais.",
    sourceSystem: "Kommo CRM; Agenda eletrônica; ERP; Prontuário eletrônico",
    storageLocation: STORAGE,
    collectionMethod: "A Coordenação Administrativa registra diariamente consultas agendadas, consultas realizadas e motivos de ausência; os dados operacionais devem ser conciliados com o Kommo CRM.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Conferência mensal entre agenda, prontuário, faturamento e Kommo CRM.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Comercial; Dashboard Executivo; Dashboard do Head de Operações",
    aiAgentName: "Agente de Relacionamento IVMM",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "COM-007",
    name: "Taxa de Conversão Comercial",
    area: "COMERCIAL",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "CLIENTES",
    strategicObjective: "Converter pacientes atendidos em clientes dos programas terapêuticos e de acompanhamento do IVMM.",
    type: "EFETIVIDADE",
    level: "ESTRATEGICO",
    polarity: "MAIOR_MELHOR",
    unit: "%",
    collectionFrequency: "DIARIA",
    analysisFrequency: "MENSAL",
    purpose: "Avaliar a eficiência da equipe comercial e assistencial na apresentação e fechamento das propostas terapêuticas.",
    operationalDefinition: "Considera compra toda contratação de consulta, procedimento, programa ou plano de acompanhamento realizada imediatamente após o atendimento.",
    formula: "(Número de Pacientes que Compraram / Número de Pacientes que Compareceram) x 100",
    numerator: "Pacientes que compraram",
    denominator: "Pacientes que compareceram",
    inclusionCriteria: "Programas de emagrecimento; Programas de longevidade; Procedimentos; Pacotes; Assinaturas.",
    exclusionCriteria: "Orçamentos pendentes; Propostas em negociação; Compras canceladas antes da efetivação.",
    sourceSystem: "Kommo CRM; ERP; Sistema Financeiro",
    storageLocation: STORAGE,
    collectionMethod: "A Coordenação Administrativa registra diariamente comparecimentos, compras realizadas e valor da venda; os dados operacionais devem ser conciliados com o Kommo CRM.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Conferência mensal entre contratos assinados, faturamento, ERP e Kommo CRM.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Comercial; Dashboard Financeiro; Dashboard Executivo",
    aiAgentName: "Agente Comercial IVMM",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "FIN-004",
    name: "Ticket Médio por Venda",
    area: "FINANCEIRO",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "FINANCEIRA",
    strategicObjective: "Maximizar a receita gerada por cada venda realizada.",
    type: "FINANCEIRO",
    level: "ESTRATEGICO",
    polarity: "MAIOR_MELHOR",
    unit: "R$",
    collectionFrequency: "DIARIA",
    analysisFrequency: "MENSAL",
    purpose: "Mensurar o valor médio de cada venda efetuada no IVMM.",
    operationalDefinition: "Representa o valor médio gerado por cada venda concluída, independentemente do serviço contratado.",
    formula: "Valor Total das Vendas / Número de Compras",
    numerator: "Valor total das vendas",
    denominator: "Número de compras",
    inclusionCriteria: "Programas; Consultas; Procedimentos; Pacotes.",
    exclusionCriteria: "Cancelamentos; Estornos; Cortesias.",
    sourceSystem: "ERP; Sistema Financeiro; Relatórios de faturamento; Kommo CRM",
    storageLocation: STORAGE,
    collectionMethod: "A Coordenação Administrativa registra diariamente valor bruto das vendas e quantidade de vendas efetivadas; os dados operacionais devem ser conciliados com o Kommo CRM quando a venda nascer do funil comercial.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Conferência mensal entre ERP, sistema financeiro, faturamento e Kommo CRM.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Financeiro; Dashboard Executivo",
    aiAgentName: "Agente Comercial IVMM",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "COM-008",
    name: "Índice de Perda Comercial",
    area: "COMERCIAL",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "CLIENTES",
    strategicObjective: "Reduzir perdas no fechamento comercial e aumentar a conversão dos pacientes atendidos.",
    type: "QUALIDADE",
    level: "ESTRATEGICO",
    polarity: "MENOR_MELHOR",
    unit: "%",
    collectionFrequency: "DIARIA",
    analysisFrequency: "MENSAL",
    purpose: "Mensurar o percentual de pacientes que, mesmo comparecendo ao atendimento, não aderiram a nenhum serviço, programa ou tratamento ofertado.",
    operationalDefinition: "Paciente perdido é aquele que compareceu ao atendimento, recebeu orientação e proposta compatível com sua indicação clínica, mas não efetivou nenhuma contratação até o encerramento do atendimento.",
    formula: "(Número de Pacientes que Não Compraram / Número de Pacientes que Compareceram) x 100",
    numerator: "Pacientes que não compraram",
    denominator: "Pacientes que compareceram",
    inclusionCriteria: "Compareceu à consulta; Recebeu proposta; Não realizou compra.",
    exclusionCriteria: "Pacientes em período de decisão previamente pactuado; Pacientes encaminhados para tratamento externo; Casos em que não houve indicação terapêutica.",
    sourceSystem: "Kommo CRM; ERP; Sistema Financeiro; Registro obrigatório do motivo da não compra",
    storageLocation: STORAGE,
    collectionMethod: "A Coordenação Administrativa registra diariamente pacientes que compareceram, pacientes que não compraram, motivo padronizado da não compra e classificação da perda; os dados operacionais devem ser conciliados com o Kommo CRM.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Revisão amostral mensal das justificativas registradas e dos motivos recorrentes no Kommo CRM.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Comercial; Dashboard Executivo; Dashboard de Performance Comercial",
    aiAgentName: "Agente de Inteligência Comercial IVMM",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
];

export async function syncCommercialFunnelIndicators(
  prisma: PrismaClient,
  actor = { name: "Administrador IVMM", role: "ADMINISTRADOR" },
) {
  for (const indicator of commercialFunnelIndicators) {
    await prisma.indicator.upsert({
      where: { code: indicator.code },
      create: indicator,
      update: indicator,
    });
  }

  await prisma.auditLog.create({
    data: {
      entity: "Indicador",
      action: "SINCRONIZAR FUNIL COMERCIAL",
      summary: `${commercialFunnelIndicators.length} indicadores comerciais integráveis ao Kommo sincronizados.`,
      actorName: actor.name,
      actorRole: actor.role,
    },
  });
}
