import type { PrismaClient } from "@prisma/client";

const COLLECTION_OWNER = "Coordenação Administrativa";
const ANALYSIS_OWNER = "Head de Operações";
const STORAGE = "Banco de Indicadores IVMM";

export const officialIndicators = [
  {
    code: "COM-001",
    name: "Taxa de Conversão de Leads em Pacientes",
    area: "COMERCIAL",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "CLIENTES",
    strategicObjective: "Aumentar a conversão dos interessados em pacientes ativos.",
    organizationalGoal: "Expandir o crescimento sustentável do IVMM. KR: aumentar a taxa de conversão de leads em 20%.",
    type: "EFICACIA",
    level: "ESTRATEGICO",
    polarity: "MAIOR_MELHOR",
    unit: "%",
    collectionFrequency: "DIARIA",
    analysisFrequency: "MENSAL",
    purpose: "Medir o percentual de leads captados que efetivamente realizam consulta inicial no Instituto.",
    operationalDefinition: "Lead é a pessoa que entrou em contato demonstrando interesse nos serviços do IVMM. Paciente convertido é o lead que realizou efetivamente a primeira consulta.",
    formula: "(Quantidade de pacientes que realizaram consulta inicial / Quantidade total de leads captados) x 100",
    numerator: "Quantidade de pacientes que realizaram consulta inicial",
    denominator: "Quantidade total de leads captados",
    inclusionCriteria: "WhatsApp; Instagram; Facebook; Site; Indicação; Eventos; Campanhas de tráfego pago.",
    exclusionCriteria: "Funcionários; Testes internos; Duplicidades; Leads sem identificação mínima.",
    sourceSystem: "CRM; WhatsApp Business; Agenda; Planilha Comercial IVMM",
    storageLocation: STORAGE,
    collectionMethod: "Registrar todos os leads e as consultas realizadas; consolidar mensalmente; alimentar o dashboard.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Conferência entre CRM, agenda e faturamento.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Comercial; Dashboard Executivo; Dashboard Conselho Consultivo",
    aiAgentName: "Agente Comercial IVMM",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "COM-002",
    name: "Custo por Lead (CPL)",
    area: "COMERCIAL",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "FINANCEIRA",
    strategicObjective: "Reduzir custo de aquisição mantendo qualidade dos leads.",
    type: "EFICIENCIA",
    level: "TATICO",
    polarity: "MENOR_MELHOR",
    unit: "R$",
    collectionFrequency: "MENSAL",
    analysisFrequency: "MENSAL",
    purpose: "Medir quanto o IVMM investe para gerar cada lead.",
    operationalDefinition: "Considera os investimentos diretamente relacionados à geração de leads nos canais oficiais do IVMM.",
    formula: "Investimento em Marketing / Número de Leads Gerados",
    numerator: "Investimento em Marketing",
    denominator: "Número de Leads Gerados",
    inclusionCriteria: "Tráfego pago; Produção de conteúdo; Ferramentas de marketing.",
    exclusionCriteria: "Custos administrativos gerais; Custos assistenciais.",
    sourceSystem: "Meta Ads; Google Ads; Financeiro; CRM",
    storageLocation: STORAGE,
    collectionMethod: "Consolidar mensalmente os investimentos de marketing e os leads gerados.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Auditoria mensal pela Coordenação Administrativa.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Comercial; Dashboard Executivo",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "COM-003",
    name: "Taxa de Comparecimento",
    area: "COMERCIAL",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "CLIENTES",
    strategicObjective: "Aumentar o comparecimento às consultas agendadas.",
    type: "EFICACIA",
    level: "OPERACIONAL",
    polarity: "MAIOR_MELHOR",
    unit: "%",
    collectionFrequency: "MENSAL",
    analysisFrequency: "MENSAL",
    purpose: "Medir o percentual de consultas agendadas efetivamente realizadas.",
    operationalDefinition: "Considera as consultas presenciais e online efetivamente realizadas em relação ao total agendado.",
    formula: "(Consultas Realizadas / Consultas Agendadas) x 100",
    numerator: "Consultas realizadas",
    denominator: "Consultas agendadas",
    inclusionCriteria: "Consultas presenciais; Consultas online.",
    exclusionCriteria: "Reagendamentos autorizados; Fechamentos institucionais.",
    sourceSystem: "Agenda; ERP; CRM",
    storageLocation: STORAGE,
    collectionMethod: "Consolidar mensalmente as consultas agendadas e realizadas.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Auditoria mensal dos registros de agenda, ERP e CRM.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Comercial; Dashboard Executivo",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "FIN-001",
    name: "Ticket Médio por Paciente",
    area: "FINANCEIRO",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "FINANCEIRA",
    strategicObjective: "Aumentar a receita média gerada por paciente.",
    organizationalGoal: "Aumentar a sustentabilidade financeira do IVMM. KR: elevar o ticket médio em 15%.",
    type: "EFICACIA",
    level: "ESTRATEGICO",
    polarity: "MAIOR_MELHOR",
    unit: "R$",
    collectionFrequency: "DIARIA",
    analysisFrequency: "MENSAL",
    purpose: "Medir quanto cada paciente gera de receita, em média, para o Instituto.",
    operationalDefinition: "Considera toda receita proveniente de consultas, procedimentos, programas, planos e acompanhamentos.",
    formula: "Receita Total / Número de Pacientes Atendidos",
    numerator: "Receita total",
    denominator: "Número de pacientes atendidos",
    inclusionCriteria: "Consultas; Procedimentos; Programas terapêuticos; Planos de acompanhamento; Pacotes assistenciais.",
    exclusionCriteria: "Receitas extraordinárias; Doações; Receitas não assistenciais.",
    sourceSystem: "Sistema Financeiro; ERP; Relatórios bancários; Dashboard Financeiro",
    storageLocation: STORAGE,
    collectionMethod: "Consolidar faturamento mensal e número de pacientes; calcular a média.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Conferência mensal dos registros financeiros e assistenciais.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Financeiro; Dashboard Executivo; Dashboard Conselho Consultivo",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "FIN-002",
    name: "Receita Recorrente Mensal (MRR)",
    area: "FINANCEIRO",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "FINANCEIRA",
    strategicObjective: "Aumentar previsibilidade financeira.",
    organizationalGoal: "Meta definida anualmente no planejamento estratégico; mínimo de 90% da meta anual projetada.",
    type: "EFETIVIDADE",
    level: "ESTRATEGICO",
    polarity: "MAIOR_MELHOR",
    unit: "R$",
    collectionFrequency: "MENSAL",
    analysisFrequency: "MENSAL",
    purpose: "Medir a receita contratada que se repete mensalmente.",
    operationalDefinition: "Somatório das receitas recorrentes mensais provenientes de contratos, programas e acompanhamentos contínuos.",
    formula: "Somatório das Receitas Recorrentes Mensais",
    numerator: "Receitas recorrentes mensais",
    inclusionCriteria: "Assinaturas; Programas mensais; Acompanhamentos contínuos; Contratos recorrentes.",
    exclusionCriteria: "Procedimentos avulsos; Consultas isoladas; Receitas extraordinárias.",
    sourceSystem: "Sistema Financeiro; ERP; Contratos ativos",
    storageLocation: STORAGE,
    collectionMethod: "Consolidar mensalmente as receitas dos contratos e programas ativos.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Auditoria mensal dos contratos e registros financeiros.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Financeiro; Dashboard Executivo; Dashboard Conselho Consultivo",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "FIN-003",
    name: "Margem Líquida",
    area: "FINANCEIRO",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "FINANCEIRA",
    strategicObjective: "Garantir sustentabilidade econômica.",
    type: "EFETIVIDADE",
    level: "ESTRATEGICO",
    polarity: "MAIOR_MELHOR",
    unit: "%",
    collectionFrequency: "MENSAL",
    analysisFrequency: "MENSAL",
    purpose: "Medir o percentual da receita que permanece após todas as despesas.",
    operationalDefinition: "Considera todas as receitas operacionais, custos e despesas do período.",
    formula: "(Lucro Líquido / Receita Total) x 100",
    numerator: "Lucro líquido",
    denominator: "Receita total",
    inclusionCriteria: "Todas as receitas operacionais; Todos os custos; Todas as despesas.",
    exclusionCriteria: "Eventos extraordinários não recorrentes.",
    sourceSystem: "DRE; Sistema Financeiro; Contabilidade",
    storageLocation: STORAGE,
    collectionMethod: "Consolidar mensalmente a DRE e calcular a margem líquida.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Auditoria mensal da DRE, sistema financeiro e contabilidade.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Financeiro; Dashboard Executivo; Dashboard Conselho Consultivo",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "OPE-001",
    name: "Taxa de Ocupação da Agenda",
    area: "OPERACOES",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "PROCESSOS_INTERNOS",
    strategicObjective: "Maximizar a utilização da capacidade assistencial do IVMM.",
    organizationalGoal: "Aumentar a eficiência operacional. KR: manter ocupação média acima de 85%.",
    type: "EFICIENCIA",
    level: "TATICO",
    polarity: "MAIOR_MELHOR",
    unit: "%",
    collectionFrequency: "DIARIA",
    analysisFrequency: "MENSAL",
    purpose: "Medir o percentual dos horários disponíveis que foram efetivamente ocupados por pacientes.",
    operationalDefinition: "Considera todos os horários disponibilizados para atendimento clínico, nutricional, psicológico, fisioterapêutico ou demais serviços oferecidos pelo IVMM.",
    formula: "(Horários Ocupados / Horários Disponíveis) x 100",
    numerator: "Horários ocupados",
    denominator: "Horários disponíveis",
    inclusionCriteria: "Consultas realizadas; Consultas confirmadas; Procedimentos agendados.",
    exclusionCriteria: "Bloqueios administrativos; Feriados; Férias; Horários de treinamento; Indisponibilidade por manutenção.",
    sourceSystem: "Agenda eletrônica; ERP; Sistema de agendamento",
    storageLocation: STORAGE,
    collectionMethod: "Extrair a agenda do período; identificar horários disponíveis e ocupados; consolidar o indicador.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Conferência entre agenda e faturamento.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Operacional; Dashboard Executivo; Dashboard Conselho Consultivo",
    aiAgentName: "Agente de Gestão Assistencial IVMM",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "OPE-002",
    name: "Tempo Médio de Resposta ao Paciente",
    area: "OPERACOES",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "CLIENTES",
    strategicObjective: "Garantir agilidade no atendimento e excelência na experiência do paciente.",
    type: "EFICIENCIA",
    level: "OPERACIONAL",
    polarity: "MENOR_MELHOR",
    unit: "minutos",
    collectionFrequency: "MENSAL",
    analysisFrequency: "MENSAL",
    purpose: "Medir o tempo médio entre o primeiro contato do paciente e a primeira resposta recebida pelo IVMM.",
    operationalDefinition: "Considera qualquer solicitação recebida por canais oficiais do Instituto.",
    formula: "Somatório dos tempos de resposta / Número de solicitações respondidas",
    numerator: "Somatório dos tempos de resposta",
    denominator: "Número de solicitações respondidas",
    inclusionCriteria: "WhatsApp; Instagram; Site; E-mail; Telefone.",
    exclusionCriteria: "Mensagens automáticas; Spam; Mensagens duplicadas.",
    sourceSystem: "WhatsApp Business; CRM; Plataforma de atendimento; Telefonia",
    storageLocation: STORAGE,
    collectionMethod: "Registrar horário de entrada e da primeira resposta; calcular a diferença; consolidar a média.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Amostragem mensal de conversas.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Operacional; Dashboard Executivo",
    aiAgentName: "Assistente Virtual IVMM",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "OPE-003",
    name: "Produtividade por Médico",
    area: "OPERACOES",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "PROCESSOS_INTERNOS",
    strategicObjective: "Aumentar a eficiência assistencial mantendo qualidade.",
    organizationalGoal: "Meta definida individualmente por especialidade.",
    type: "EFICIENCIA",
    level: "OPERACIONAL",
    polarity: "MAIOR_MELHOR",
    unit: "pacientes por turno",
    collectionFrequency: "MENSAL",
    analysisFrequency: "MENSAL",
    purpose: "Medir a produção média individual de cada médico do Instituto.",
    operationalDefinition: "Mensura a capacidade produtiva do profissional respeitando critérios de qualidade e segurança assistencial.",
    formula: "Número de Pacientes Atendidos / Número de Períodos Trabalhados",
    numerator: "Número de pacientes atendidos",
    denominator: "Número de períodos trabalhados",
    inclusionCriteria: "Consultas realizadas; Retornos realizados; Avaliações completas.",
    exclusionCriteria: "Faltas de pacientes; Bloqueios de agenda; Horários administrativos.",
    sourceSystem: "Agenda; ERP; Sistema de faturamento",
    storageLocation: STORAGE,
    collectionMethod: "Extrair atendimentos por médico e carga horária; calcular a produção média.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Conferência entre agenda, prontuário e faturamento.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Operacional; Dashboard Executivo",
    aiAgentName: "Analista Operacional IVMM",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "RET-001",
    name: "Lifetime Value (LTV)",
    area: "RELACIONAMENTO_RETENCAO",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "FINANCEIRA",
    strategicObjective: "Aumentar o valor gerado por cada paciente ao longo de sua permanência no IVMM.",
    organizationalGoal: "Aumentar a sustentabilidade financeira através da fidelização. KR: elevar o LTV médio em 20%.",
    type: "EFETIVIDADE",
    level: "ESTRATEGICO",
    polarity: "MAIOR_MELHOR",
    unit: "R$",
    collectionFrequency: "MENSAL",
    analysisFrequency: "TRIMESTRAL",
    purpose: "Medir o valor financeiro total gerado por um paciente durante todo o seu relacionamento com o Instituto.",
    operationalDefinition: "Representa a soma de toda receita gerada por um paciente desde sua entrada até seu desligamento ou inatividade.",
    formula: "Ticket Médio x Tempo Médio de Permanência",
    numerator: "Ticket médio por paciente",
    denominator: "Tempo médio de permanência",
    inclusionCriteria: "Consultas; Procedimentos; Programas de acompanhamento; Renovações; Pacotes terapêuticos.",
    exclusionCriteria: "Receitas extraordinárias; Receitas administrativas; Doações.",
    sourceSystem: "ERP; Sistema Financeiro; CRM",
    storageLocation: STORAGE,
    collectionMethod: "Identificar pacientes ativos; levantar histórico financeiro; calcular receita acumulada e média geral.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Conferência trimestral entre CRM e faturamento.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Financeiro; Dashboard Executivo; Dashboard Conselho Consultivo",
    aiAgentName: "Analista de Relacionamento IVMM",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "TRIMESTRAL",
  },
  {
    code: "RET-002",
    name: "Taxa de Retorno de Pacientes",
    area: "RELACIONAMENTO_RETENCAO",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: ANALYSIS_OWNER,
    status: "ATIVO",
    bscPerspective: "CLIENTES",
    strategicObjective: "Aumentar a fidelização e continuidade assistencial.",
    type: "EFICACIA",
    level: "TATICO",
    polarity: "MAIOR_MELHOR",
    unit: "%",
    collectionFrequency: "MENSAL",
    analysisFrequency: "MENSAL",
    purpose: "Medir o percentual de pacientes que retornam ao IVMM após a primeira consulta.",
    operationalDefinition: "Considera o retorno programado dentro do plano terapêutico definido pelo profissional.",
    formula: "(Pacientes que retornaram / Pacientes elegíveis para retorno) x 100",
    numerator: "Pacientes que retornaram",
    denominator: "Pacientes elegíveis para retorno",
    inclusionCriteria: "Pacientes com indicação formal de retorno; Pacientes em programas de acompanhamento.",
    exclusionCriteria: "Alta definitiva; Óbito; Mudança de cidade; Encaminhamento externo.",
    sourceSystem: "Agenda; ERP; CRM; Prontuário eletrônico",
    storageLocation: STORAGE,
    collectionMethod: "Identificar pacientes elegíveis e retornos realizados; calcular o percentual.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Conferência mensal entre agenda e prontuário.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard de Relacionamento; Dashboard Executivo; Dashboard Conselho Consultivo",
    aiAgentName: "Agente de Relacionamento IVMM",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "MENSAL",
  },
  {
    code: "RET-003",
    name: "Taxa de Adesão aos Protocolos Assistenciais",
    area: "QUALIDADE_ASSISTENCIAL",
    responsiblePrimary: COLLECTION_OWNER,
    responsibleSecondary: "Head de Operações; validação técnica pelo Diretor Clínico e Responsáveis Técnicos",
    status: "ATIVO",
    bscPerspective: "PROCESSOS_INTERNOS",
    strategicObjective: "Garantir padronização da assistência e melhores desfechos clínicos.",
    type: "QUALIDADE",
    level: "ESTRATEGICO",
    polarity: "MAIOR_MELHOR",
    unit: "%",
    collectionFrequency: "MENSAL",
    analysisFrequency: "TRIMESTRAL",
    purpose: "Medir o percentual de pacientes que seguem integralmente os protocolos definidos pelo IVMM.",
    operationalDefinition: "Paciente aderente é aquele que cumpre os requisitos mínimos previstos no protocolo clínico definido pelo IVMM.",
    formula: "(Pacientes aderentes / Pacientes incluídos em protocolo) x 100",
    numerator: "Pacientes aderentes",
    denominator: "Pacientes incluídos em protocolo",
    inclusionCriteria: "Protocolos de emagrecimento; Longevidade; Atividade física; Nutricionais; Saúde preventiva.",
    exclusionCriteria: "Pacientes recém-incluídos; Pacientes desligados; Protocolos suspensos.",
    sourceSystem: "Prontuário eletrônico; CRM; Aplicativos de acompanhamento; Relatórios assistenciais",
    storageLocation: STORAGE,
    collectionMethod: "Identificar pacientes em protocolo; avaliar critérios; classificar adesão; consolidar o indicador.",
    collectionOwner: COLLECTION_OWNER,
    evidence: "Auditoria amostral trimestral de prontuários, com validação do Diretor Clínico.",
    isAiEligible: true,
    isAiIntegrable: true,
    dashboardName: "Dashboard Assistencial; Dashboard Executivo; Dashboard Conselho Consultivo",
    aiAgentName: "Assistente Clínico IVMM",
    dataReliability: "Médio",
    requiresAudit: true,
    auditFrequency: "TRIMESTRAL",
  },
];

const officialGoals = [
  { code: "COM-001", targetValue: 35, alertValue: 20, minimumValue: 20, idealValue: 50 },
  { code: "COM-002", targetValue: 25, alertValue: 40, minimumValue: 40, idealValue: 15 },
  { code: "COM-003", targetValue: 85, alertValue: 80, minimumValue: 80, idealValue: 90 },
  { code: "FIN-001", targetValue: 350, alertValue: 250, minimumValue: 250, idealValue: 500 },
  { code: "FIN-003", targetValue: 20, alertValue: 15, minimumValue: 15, idealValue: 25 },
  { code: "OPE-001", targetValue: 85, alertValue: 75, minimumValue: 75, idealValue: 90 },
  { code: "OPE-002", targetValue: 15, alertValue: 30, minimumValue: 30, idealValue: 5 },
  { code: "OPE-003", targetValue: 10, alertValue: 8, minimumValue: 8, idealValue: 12 },
  { code: "RET-001", targetValue: 3000, alertValue: 2000, minimumValue: 2000, idealValue: 5000 },
  { code: "RET-002", targetValue: 70, alertValue: 60, minimumValue: 60, idealValue: 80 },
  { code: "RET-003", targetValue: 85, alertValue: 75, minimumValue: 75, idealValue: 90 },
];

const officialOkrs = [
  { title: "Crescimento sustentável", objective: "Expandir o crescimento sustentável do IVMM.", area: "COMERCIAL", indicators: ["COM-001"] },
  { title: "Sustentabilidade financeira", objective: "Aumentar a sustentabilidade financeira do IVMM.", area: "FINANCEIRO", indicators: ["FIN-001"] },
  { title: "Eficiência operacional", objective: "Aumentar a eficiência operacional.", area: "OPERACOES", indicators: ["OPE-001"] },
  { title: "Fidelização e sustentabilidade", objective: "Aumentar a sustentabilidade financeira através da fidelização.", area: "RELACIONAMENTO_RETENCAO", indicators: ["RET-001"] },
];

export async function loadOfficialData(
  prisma: PrismaClient,
  actor = { name: "Administrador IVMM", role: "ADMINISTRADOR" },
) {
  await prisma.$transaction(async (tx) => {
    await tx.auditLog.deleteMany({
      where: { entity: { in: ["Sistema", "Indicador", "Meta", "Resultado", "OKR"] } },
    });
    await tx.result.deleteMany();
    await tx.goal.deleteMany();
    await tx.okrIndicator.deleteMany();
    await tx.okr.deleteMany();
    await tx.indicator.deleteMany();

    await tx.indicator.createMany({ data: officialIndicators });
    const indicators = await tx.indicator.findMany({ select: { id: true, code: true } });
    const indicatorIds = new Map(indicators.map((indicator) => [indicator.code, indicator.id]));

    await tx.goal.createMany({
      data: officialGoals.map(({ code, ...goal }) => ({
        indicatorId: indicatorIds.get(code)!,
        year: 2026,
        ...goal,
      })),
    });

    for (const okrData of officialOkrs) {
      const { indicators: codes, ...data } = okrData;
      const okr = await tx.okr.create({
        data: { ...data, year: 2026, owner: ANALYSIS_OWNER },
      });
      await tx.okrIndicator.createMany({
        data: codes.map((code) => ({ okrId: okr.id, indicatorId: indicatorIds.get(code)! })),
      });
    }

    await tx.auditLog.create({
      data: {
        entity: "Sistema",
        action: "IMPORTAR FICHAS OFICIAIS",
        summary: "12 indicadores oficiais importados; resultados de teste removidos.",
        actorName: actor.name,
        actorRole: actor.role,
      },
    });
  });
}
